In [4]:
! pip install pandas numpy matplotlib seaborn scikit-learn

Collecting pandas
  Using cached pandas-2.3.1-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in f:\anconda\envs\quantanics\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in f:\anconda\envs\quantanics\lib\site-packages (3.10.3)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.7.0-cp310-cp310-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\anconda\envs\quantanics\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in f:\anconda\envs\quantanics\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: scipy>=1.8.0 in f:\anconda\envs\quantanics\lib\site-packages (from scikit-learn) (1.15.3)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in f:\anconda\envs\quantanics\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.3 MB 10.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.3 MB 9.4 MB/s eta 0:00:01
   ----------------- ---------------------- 5.0/11.3 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.3 MB 8.7 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.3 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 6.7 MB/s eta 0:00:00
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached scikit_learn-1.7.0-cp310-cp310-win_amd64.whl (10.7 MB)
Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, joblib, scikit-learn, pandas, seaborn

   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ---------------------------------------- 0/7 [pytz]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----------- ---------------------------- 2/7 [threadpoolctl]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed joblib-1.5.1 pandas-2.3.1 pytz-2025.2 scikit-learn-1.7.0 seaborn-0.13.2 threadpoolctl-3.6.0 tzdata-2025.2

In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import kstest

In [6]:
df=pd.read_csv(r'F:\quantanics\machine learning\dataset\train_JDXlpm8\train\transactions.csv')
df.head()

,doj,doi,srcid,destid,srcid_region,destid_region,srcid_tier,destid_tier,cumsum_seatcount,cumsum_searchcount,dbd
0,2023-03-01,2023-01-30,45,46,Karnataka,Tamil Nadu,Tier 1,Tier 1,8.0,76.0,30
1,2023-03-01,2023-01-30,46,45,Tamil Nadu,Karnataka,Tier 1,Tier 1,8.0,70.0,30
2,2023-03-01,2023-01-30,45,47,Karnataka,Andhra Pradesh,Tier 1,Tier 1,4.0,142.0,30
3,2023-03-01,2023-01-30,47,45,Andhra Pradesh,Karnataka,Tier 1,Tier 1,0.0,68.0,30
4,2023-03-01,2023-01-30,46,9,Tamil Nadu,Tamil Nadu,Tier 1,Tier2,9.0,162.0,30

In [9]:
df['doj']=pd.to_datetime(df['doj'])
df['doi']=pd.to_datetime(df['doi'])

In [11]:
df['doj_year'] = df['doj'].dt.year
df['doj_month'] = df['doj'].dt.month
df['doj_date'] = df['doj'].dt.day

# Split doi
df['doi_year'] = df['doi'].dt.year
df['doi_month'] = df['doi'].dt.month
df['doi_date'] = df['doi'].dt.day

In [12]:
df.head()

,doj,doi,srcid,destid,srcid_region,destid_region,srcid_tier,destid_tier,cumsum_seatcount,cumsum_searchcount,dbd,doj_year,doj_month,doj_date,doi_year,doi_month,doi_date
0,2023-03-01,2023-01-30,45,46,Karnataka,Tamil Nadu,Tier 1,Tier 1,8.0,76.0,30,2023,3,1,2023,1,30
1,2023-03-01,2023-01-30,46,45,Tamil Nadu,Karnataka,Tier 1,Tier 1,8.0,70.0,30,2023,3,1,2023,1,30
2,2023-03-01,2023-01-30,45,47,Karnataka,Andhra Pradesh,Tier 1,Tier 1,4.0,142.0,30,2023,3,1,2023,1,30
3,2023-03-01,2023-01-30,47,45,Andhra Pradesh,Karnataka,Tier 1,Tier 1,0.0,68.0,30,2023,3,1,2023,1,30
4,2023-03-01,2023-01-30,46,9,Tamil Nadu,Tamil Nadu,Tier 1,Tier2,9.0,162.0,30,2023,3,1,2023,1,30

In [15]:
df.drop(columns=['doj','doi'],inplace=True)
df

,srcid,destid,srcid_region,destid_region,srcid_tier,destid_tier,cumsum_seatcount,cumsum_searchcount,dbd,doj_year,doj_month,doj_date,doi_year,doi_month,doi_date
0,45,46,Karnataka,Tamil Nadu,Tier 1,Tier 1,8.0,76.0,30,2023,3,1,2023,1,30
1,46,45,Tamil Nadu,Karnataka,Tier 1,Tier 1,8.0,70.0,30,2023,3,1,2023,1,30
2,45,47,Karnataka,Andhra Pradesh,Tier 1,Tier 1,4.0,142.0,30,2023,3,1,2023,1,30
3,47,45,Andhra Pradesh,Karnataka,Tier 1,Tier 1,0.0,68.0,30,2023,3,1,2023,1,30
4,46,9,Tamil Nadu,Tamil Nadu,Tier 1,Tier2,9.0,162.0,30,2023,3,1,2023,1,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266095,2,24,Maharashtra and Goa,Maharashtra and Goa,Tier 1,Tier2,0.0,0.0,0,2025,2,28,2025,2,28
2266096,44,45,Tamil Nadu,Karnataka,Tier2,Tier 1,0.0,0.0,0,2025,2,28,2025,2,28
2266097,47,10,Andhra Pradesh,Andhra Pradesh,Tier 1,Tier 3,0.0,0.0,0,2025,2,28,2025,2,28
2266098,38,36,Rest of North,Delhi,Tier 1,Tier2,0.0,0.0,0,2025,2,28,2025,2,28
2266099,19,30,Madhya Pradesh,Maharashtra and Goa,Tier 1,Tier 1,0.0,0.0,0,2025,2,28,2025,2,28